# Generated by Django 4.2.5 on 2023-10-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_teacherlink_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
