# Generated by Django 4.2.5 on 2023-11-05 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_personalteacherlinks_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalteacherlinks',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
