# Generated by Django 4.2.5 on 2023-11-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_personalteacherlinks_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalteacherlinks',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
