# Generated by Django 4.2.5 on 2023-11-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_personalteacherlinks_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalteacherlinks',
            name='private',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
