# Generated by Django 4.2.5 on 2023-11-07 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_personalteacherlinks_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalteacherlinks',
            name='course',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.course'),
        ),
        migrations.AddField(
            model_name='personalteacherlinks',
            name='facult',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.facult'),
        ),
        migrations.AddField(
            model_name='personalteacherlinks',
            name='group',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.group'),
        ),
    ]
