# Generated by Django 4.2.5 on 2023-11-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_personalteacherlinks_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherlink',
            name='link',
            field=models.CharField(null=True),
        ),
    ]
