# Generated by Django 4.2.5 on 2023-11-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_personalteacherlinks_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalteacherlinks',
            name='group',
        ),
    ]
