# Generated by Django 4.2.5 on 2023-11-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_teacherlink_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherlink',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
