# Generated by Django 4.2.5 on 2023-11-12 19:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_personalteacherlinks_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalteacherlinks',
            name='group',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.group'),
        ),
        migrations.AddField(
            model_name='teacherlink',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='personalteacherlinks',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='teacherlink',
            name='link',
            field=models.CharField(null=True),
        ),
    ]
