# Generated by Django 4.2.5 on 2023-11-10 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_personalteacherlinks_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalteacherlinks',
            name='group',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.group'),
        ),
    ]
