# Generated by Django 4.2.5 on 2023-11-10 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_personalteacherlinks_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherlink',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
