# Generated by Django 4.2.5 on 2023-11-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_teacherlink_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalteacherlinks',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='teacherlink',
            name='link',
            field=models.CharField(null=True),
        ),
    ]
