# Generated by Django 4.2.5 on 2023-11-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_personalteacherlinks_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalteacherlinks',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherlink',
            name='link',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
