# Generated by Django 4.2.5 on 2023-10-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_course2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course2',
        ),
    ]
