# Generated by Django 4.2.5 on 2023-10-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_user_course2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherlink',
            name='link',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
