# Generated by Django 4.2.5 on 2023-11-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_personalteacherlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalteacherlinks',
            name='private',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
