# Generated by Django 4.2.5 on 2023-11-10 20:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_personalteacherlinks_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalteacherlinks',
            name='group',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.group'),
        ),
        migrations.AddField(
            model_name='teacherlink',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
