# Generated by Django 4.2.5 on 2023-11-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_personalteacherlinks_group_teacherlink_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalteacherlinks',
            name='link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='teacherlink',
            name='link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
