# Generated by Django 4.2.5 on 2024-09-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_teacherlink_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_graduate',
            field=models.BooleanField(default=False),
        ),
    ]
