# Generated by Django 4.2.5 on 2023-10-22 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_teacherlink_faculty_alter_teacherlink_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='facult',
        ),
        migrations.AddField(
            model_name='user',
            name='facult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.facult'),
        ),
    ]
