# Generated by Django 4.2.5 on 2023-10-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_schedules_date_alter_schedules_facult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='name2',
            field=models.CharField(default='sd', max_length=150, verbose_name='Пример: "3 курс ИСИП"'),
        ),
    ]
