# Generated by Django 4.2.5 on 2023-10-20 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_user_course2'),
        ('lessons', '0010_rename_schedule_rpd_rpd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='name2',
        ),
        migrations.AddField(
            model_name='schedules',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.course'),
        ),
    ]
