# Generated by Django 4.2.5 on 2023-10-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_course_facult_user_facult'),
        ('lessons', '0015_remove_schedules_facult'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='facult',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.facult'),
        ),
    ]
