# Generated by Django 4.2.5 on 2023-11-10 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_personalteacherlinks_link_and_more'),
        ('lessons', '0018_lecture_course_lecture_facult_lecture_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('facult', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.facult')),
            ],
            options={
                'verbose_name': 'Проф. БД',
                'verbose_name_plural': 'Проф. БД',
            },
        ),
    ]
