# Generated by Django 4.2.5 on 2024-03-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0021_alter_lecture_title_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='review_files', verbose_name='Файл'),
        ),
    ]
