# Generated by Django 4.2.5 on 2023-09-26 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lecture_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='slug',
        ),
    ]
