# Generated by Django 4.2.5 on 2023-10-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_schedules_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='name2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Пример: "3 курс ИСИП"'),
        ),
    ]
