# Generated by Django 4.2.5 on 2023-10-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_schedules_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Пример: "3 курс ИСИП"')),
                ('schedule', models.FileField(max_length=300, upload_to='', verbose_name='Файл с РПД')),
            ],
            options={
                'verbose_name': 'РПД',
                'verbose_name_plural': 'РПД',
            },
        ),
    ]
