# Generated by Django 4.2.5 on 2023-10-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_alter_rpd_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpd',
            old_name='title',
            new_name='course',
        ),
    ]
