# Generated by Django 4.2.5 on 2023-10-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_course_alter_user_facult'),
        ('lessons', '0016_schedules_facult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpd',
            name='course',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.course'),
        ),
        migrations.AlterField(
            model_name='rpd',
            name='facult',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.facult'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='course',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.course'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='facult',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.facult'),
        ),
    ]
