# Generated by Django 4.2.5 on 2023-10-30 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_group_teacherlink_group_user_group'),
        ('lessons', '0017_alter_rpd_course_alter_rpd_facult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.course'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='facult',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.facult'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='group',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.group'),
        ),
    ]
