# Generated by Django 4.2.5 on 2023-10-30 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_group_teacherlink_group_user_group'),
        ('lessons', '0018_lecture_course_lecture_facult_lecture_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='group',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.group'),
        ),
    ]
