# Generated by Django 4.2.5 on 2023-11-10 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0019_profdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='course',
        ),
        migrations.RemoveField(
            model_name='schedules',
            name='group',
        ),
    ]
