# Generated by Django 4.2.5 on 2023-11-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0019_schedules_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='schedule',
            field=models.CharField(max_length=300, verbose_name='PDF ссылка на расписание'),
        ),
    ]
