# Generated by Django 4.2.5 on 2023-11-12 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_teacherlink_link'),
        ('lessons', '0020_remove_schedules_course_remove_schedules_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedules',
            name='course',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.course'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='group',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.group'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='ProfDB',
        ),
    ]
