# Generated by Django 4.2.5 on 2023-11-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0020_alter_schedules_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='schedule',
            field=models.CharField(max_length=300, verbose_name='Ссылка на расписание'),
        ),
    ]
