# Generated by Django 4.2.5 on 2023-11-12 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_teacherlink_link'),
        ('lessons', '0021_schedules_course_schedules_group_alter_lecture_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedules',
            name='course',
        ),
        migrations.RemoveField(
            model_name='schedules',
            name='group',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='ProfDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('facult', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.facult')),
            ],
            options={
                'verbose_name': 'Проф. БД',
                'verbose_name_plural': 'Проф. БД',
            },
        ),
    ]
