# Generated by Django 4.2.5 on 2023-11-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0021_alter_schedules_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='schedule',
            field=models.FileField(max_length=300, upload_to='', verbose_name='PDF ссылка на расписание'),
        ),
    ]
