# Generated by Django 4.2.5 on 2023-11-13 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0024_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='parent',
        ),
    ]
