# Generated by Django 4.2.5 on 2023-11-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0024_alter_lecture_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
    ]
